### ISSUE TITLE
Use unity 5?

### ISSUE THREAD

**Issue by ferhtgoldaraz** [Menzuals/Chessaken#1]
Qué pasa tron! Mucha suerte con esto!

I was checking this out and Unity asked me to upgrade the project. Maybe use unity 5, or is it due to some other thing?

Are there any advantages to using an older version?

**Comment by datMen** [comment]
Jajajaja muchas gracias tio!! A ver si no se me va de madre :D

Actually I didn't think about it, I should have started the project in unity 5 but I had Unity 4 already installed, I'm not sure if I move to 5 now all the models will keep fine :/
