### ISSUE TITLE
Bug on piece allowed movements not always right

### ISSUE THREAD

**Issue by glantucan** [Menzuals/Chessaken#2]
I found various situations in which the allowed movements algorithm doesn't find the proper solutions. Here you have one with the black bishop. 
![chessaken_bug01](https://cloud.githubusercontent.com/assets/1677172/8451848/a3c0b4c2-1fe6-11e5-9e60-ea58fdb83a1c.jpg)
![chessaken_bug02](https://cloud.githubusercontent.com/assets/1677172/8451874/d7799914-1fe6-11e5-887d-55eb3c01fe4a.jpg)

**Comment by glantucan** [comment]
Nice game, btw. ;)

**Comment by datMen** [comment]
Hah thank you :D. If you move that bishop you leave the king in check (because of the white queen), thats why it has 0 allowed movements

**Comment by glantucan** [comment]
:O That's right!. My mistake
